Repository microsoft/DirectXMesh, pull requests merged in 2024-01, with the labels that each got.

#119 December 31, 2023
  .nuget/directxmesh_desktop_2019.nuspec
  .nuget/directxmesh_desktop_win10.nuspec
  .nuget/directxmesh_uwp.nuspec
  CMakeLists.txt
  DirectXMesh/DirectXMesh.h
  HISTORY.md
  README.md
Labels: maintainence

#121 Fix build warnings with MinGW 13.2
  CMakeLists.txt
  DirectXMesh/DirectXMeshRemap.cpp
Labels: conformance

#122 CMake update to install EXEs
  CMakeLists.txt
Labels: tools

#123 CMake code review
  CMakeLists.txt
Labels: maintainence
